

[dev]
  framework = "#custom"
  command = "yarn start" # Command to start your dev server
  port = 8888 # The port that the netlify dev will be accessible on
  targetPort = 8080
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

[[edge_functions]]
  path = "/geolocation"
  function = "geolocation"
